# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZ1bFt5JOhYcgBfIh4nj9_VyxUiYvUNk
"""

import random #random kütüphanesi rastgele seçim yapmamızı sağlıyor
import unicodedata #Türkçe karakteri normalize etmemizi sağlıyor

#Görseller
oyun_resimleri = ['''tas:
    _______
---'   ____
      (_____)
      (_____)
      (____)
---.__(___)
''',
'''kagit:
    _______
---'   ____)____
          ______)
          _______)
         _______)
---.__________)
''',
'''makas:
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
''']


secenekler = ["tas", "kagit", "makas"]

def normalize_girdi(girdi):
    # Türkçe karakterleri normalize etmemizi sağlıyor
    girdi = unicodedata.normalize('NFKC', girdi)
    # Küçük harfe çevirmemizi sağlıyor
    girdi = girdi.lower()
    # Türkçe karakterleri değiştirerek oyun esnasında sıkıntı çıkmasını engellemek amaçlanmıştır.
    girdi = girdi.replace('ş', 's').replace('ı', 'i').replace('ç', 'c').replace('ğ', 'g').replace('ü', 'u').replace('ö', 'o')
    return girdi

def tas_kagit_makas_Betul_Cinbaroglu():
    def oyun_oyna(oyun_sayisi):
        pc_skor = 0
        kullanici_skor = 0

        print(f"\n** {oyun_sayisi}. OYUN **")
        print("!!TAŞ KAGIT MAKAS OYUNUNA HOŞGELDİNİZ!!")
        print("Oyunumuzu sana tanıtmak istiyorum.\nTaşı seçersen makası yener, kağıda yenilirsin.\nKağıdı seçersen taşı yener, makasa yenilirsin.\nMakası seçersen kağıdı yener, taşa yenilirsin.")
        print("İki oyuncudan biri 2 puana ulaştığında oyun bitmektedir.")
        print("Oyunun kurallarını öğrendiğine göre oyuna başlayabiliriz.")

        while pc_skor < 2 and kullanici_skor < 2:
            kullanici_secimi = normalize_girdi(input("Taş, kağıt veya makas seçin: "))

            # Geçerli seçimler
            if kullanici_secimi not in secenekler:
                print("Geçersiz bir seçim yaptınız! Lütfen 'tas', 'kagit' veya 'makas' yazın.")
                continue  # Döngüyü yeniden başlatır ve kullanıcıdan tekrar seçim yapmasını ister

            bilgisayar_secimi = random.choice(secenekler)

            # Seçimlerin görselleri
            kullanici_gorsel = oyun_resimleri[secenekler.index(kullanici_secimi)]
            bilgisayar_gorsel = oyun_resimleri[secenekler.index(bilgisayar_secimi)]

            print(f"Kullanıcı seçimi:\n{kullanici_gorsel}")
            print(f"Bilgisayar seçimi:\n{bilgisayar_gorsel}")

            # Sonuçları belirleme
            if kullanici_secimi == bilgisayar_secimi:
                print("Bu el berabere!")
            elif (kullanici_secimi == "tas" and bilgisayar_secimi == "makas") or \
                 (kullanici_secimi == "kagit" and bilgisayar_secimi == "tas") or \
                 (kullanici_secimi == "makas" and bilgisayar_secimi == "kagit"):
                print("Bu eli kazandınız!")
                kullanici_skor += 1
            else:
                print("Bu eli kaybettiniz!")
                pc_skor += 1

            print(f"Sizin skorunuz: {kullanici_skor} - Bilgisayarın skoru: {pc_skor}")

        if pc_skor > kullanici_skor:
            print("PC kazandı :(")
        else:
            print("Tebrikler, kazandınız! :)")

    oyun_sayisi = 1  # Oyun sayacı
    while True:
        oyun_oyna(oyun_sayisi)
        oyun_sayisi += 1  # Oyun sayısını bir artır

        # Kullanıcıya oyuna devam edip etmek istemediği sorulur
        devam_mi = normalize_girdi(input("Tekrar oynamak ister misiniz? (evet/hayir): "))

        # Bilgisayarın oyuna devam edip etmek istemediği rastgele belirlenir
        bilgisayar_devam = random.choice([True, False])
        print(f"Bilgisayar tekrar oynamak istiyor mu?: {'Evet' if bilgisayar_devam else 'Hayır'}")

        # Hem kullanıcı hem de bilgisayar devam etmek istemiyorsa oyun sona erer
        if devam_mi != "evet" or not bilgisayar_devam:
            print("Oyun sona erdi. Teşekkürler!")
            break

if __name__ == "__main__":
    tas_kagit_makas_Betul_Cinbaroglu()